import type { ViewerBundle } from "../api/schemas";
import { vi } from "vitest";

export const bundle: ViewerBundle = {
  workflow_id: "wf_1",
  status: "completed",
  generation_mode: "real_blender",
  generation_strategy: "parametric_scene_spec",
  geometry_source: "scene_spec",
  mesh_qa_level: "mesh_level_basic",
  mesh_qa_passed: false,
  qa_score: 0.67,
  asset_import_summary: null,
  human_warnings_count: 1,
  human_errors_count: 0,
  primary_glb_url: "/designs/wf_1/artifacts/design.glb",
  preview_url: "/designs/wf_1/artifacts/preview.png",
  report_url: null,
  metadata_url: null,
  scene_spec_url: null,
  qa_report_url: null,
  generation_report_url: null,
  geometry_validation_url: null,
  rag_evidence_url: null,
  requirements_spec_url: null,
  extraction_report_url: null,
  llm_provider: "groq",
  llm_available: true,
  llm_fallback_used: false,
  llm_fallback_reason: null,
  rag_context_count: 0,
  rag_planning_summary: null,
  rag_reranker_provider: "nvidia",
  rag_reranker_model: "nvidia/llama-3.2-nv-rerankqa-1b-v2",
  rag_reranker_status: "passthrough",
  rag_reranker_degraded_reason: "NVIDIA reranker unavailable",
  memory_context_count: 0,
  qa_summary: {
    checks_passed: [],
    checks_failed: [],
    warnings: [],
    errors: [],
    upstream_errors: [],
    limitations: []
  },
  viewer_artifacts: [],
  limitations: [],
  unsupported_actions: [{ action: "download_artifacts", reason: "missing artifact" }],
  available_actions: []
};

export const commandDefaults = {
  analysis: null,
  analysisBusy: false,
  analysisError: null,
  analysisSubmitted: false,
  canEdit: false,
  documentCapabilities: null,
  documentPackBusy: false,
  documentPackMessage: null,
  documentPackSummary: null,
  editMessage: null,
  error: null,
  onAnalyze: vi.fn(),
  onConfirm: vi.fn(),
  onDocumentPackUpload: vi.fn(),
  onPromptChange: vi.fn(),
  onRevisionPromptChange: vi.fn(),
  onRevisionSubmit: vi.fn(),
  phase: "idle" as const,
  prompt: "",
  submissionPending: false,
  revisionBusy: false,
  revisionPrompt: ""
};

export const parsedRequirements = {
  requirements: {
    network_type: "5G",
    site_type: "telecom_site",
    tower_type: "lattice_tower",
    tower_height_m: 30,
    tower_characteristics: {
      structure: "lattice",
      leg_count: 4,
      base_width_m: 4,
      top_width_m: 1,
      foundation_type: "concrete_pad",
      material: "galvanized_steel"
    },
    sector_count: 3,
    antenna_type: "panel_5g",
    antenna_install_height_m: 24,
    azimuths_deg: [0, 120, 240],
    mechanical_tilt_deg: 3,
    electrical_tilt_deg: 0,
    beamwidth_deg: 65,
    include_rru: true,
    include_cables: true,
    include_beams: true,
    include_labels: true,
    include_power_cabinet: true,
    include_gps_antenna: true,
    geometry_requests: [],
    detail_level: "high",
    warnings: [],
    repair_events: [],
    field_evidence: {},
    conflicts: [],
    assumptions: [],
    requires_confirmation: false,
    confirmation_fields: []
  },
  requirements_hash: "a".repeat(64),
  warnings: [],
  errors: [],
  provider: "groq:openai/gpt-oss-120b",
  extraction_provider: "llm",
  fallback_used: false,
  llm_fallback_reason: null,
  analysis_receipt: {
    schema_version: "1.0.0" as const,
    receipt_id: `ira_${"a".repeat(32)}`,
    issued_at: "2026-09-11T10:00:00+00:00",
    confirmed_prompt_sha256: "b".repeat(64),
    confirmed_requirements_sha256: "c".repeat(64),
    detail_level: "high" as const,
    provider: "groq:openai/gpt-oss-120b",
    model: "openai/gpt-oss-120b",
    extraction_provider: "llm",
    fallback_used: false,
    fallback_reason: null
  }
};
