"""Parametric model resolver.

Decides how each object in a SceneSpec should be produced:
- parametric_generated
- imported_glb_exact
- stretched_imported_glb
- internal_project_generated
- procedural_fallback
- degraded

This module is pure Python (no bpy) and can be unit-tested independently.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Literal

from core.contracts.assets import AssetManifest
from core.contracts.parametric import GenerationStrategy, GeometrySource
from core.contracts.scene import SceneAccessoryPlacement, SceneAssetPlacement, SceneSpec, SectorSpec
from core.services.asset_registry import AssetRegistry

logger = logging.getLogger(__name__)


class ParametricModelResolver:
    """Decides generation strategy for every object in a SceneSpec."""

    # Relative tolerance used to decide whether an existing GLB is an exact fit.
    EXACT_DIMENSION_TOLERANCE = 0.01  # 1%

    def __init__(self, registry: AssetRegistry | None = None) -> None:
        self.registry = registry or AssetRegistry(Path("assets/manifests"))
        self._assets: dict[str, AssetManifest] | None = None

    def _asset(self, asset_id: str) -> AssetManifest | None:
        if self._assets is None:
            self._assets = {a.asset_id: a for a in self.registry.list_assets()}
        return self._assets.get(asset_id)

    def resolve_tower(
        self, placement: SceneAssetPlacement
    ) -> tuple[GenerationStrategy, GeometrySource, str, list[str]]:
        """Towers should be parametrically generated by default.

        We only import a GLB exactly if an exact match exists AND the project
        explicitly prefers assets over parametric generation. Otherwise the
        geometry is driven by SceneSpec characteristics to avoid stretching.
        """
        warnings: list[str] = []
        requested = placement.dimensions_m
        asset = self._asset(placement.asset_id)

        if asset is None:
            return (
                "parametric_generated",
                "parametric_generated",
                "no manifest found for requested tower; generating from SceneSpec characteristics",
                warnings,
            )

        if requested is not None and asset.dimensions_m is not None:
            exact = self._dimensions_match(requested, asset.dimensions_m)
            if exact and asset.source in {"cc_by", "vendor_supplied", "vendor_expected"}:
                return (
                    "imported_glb_exact",
                    "imported_glb_exact",
                    f"exact validated GLB available for {placement.asset_id}",
                    warnings,
                )
            if not exact:
                warnings.append(
                    f"REQUESTED_TOWER_DIMENSIONS_DIFFER_FROM_ASSET:{placement.asset_id}"
                )
                # Even if an asset exists, do not stretch it: generate parametrically.
                reason = (
                    f"asset {placement.asset_id} dimensions do not match request; "
                    "generating parametrically"
                )
                return (
                    "parametric_generated",
                    "parametric_generated",
                    reason,
                    warnings,
                )

        # Internal generated/cleaned/test assets: keep as internal_project_generated
        # unless dimensions mismatch, in which case parametric is preferred.
        if asset.source in {
            "internal_project_generated",
            "internal_cleaned",
            "internal_test_minimal",
        }:
            if requested is not None and asset.dimensions_m is not None:
                if not self._dimensions_match(requested, asset.dimensions_m):
                    warnings.append(
                        f"INTERNAL_TOWER_ASSET_DIMENSIONS_MISMATCH:{placement.asset_id}"
                    )
                    return (
                        "parametric_generated",
                        "parametric_generated",
                        (
                            f"internal asset {placement.asset_id} does not match requested "
                            "dimensions; generating parametrically"
                        ),
                        warnings,
                    )
            return (
                "internal_project_generated",
                "internal_project_generated",
                f"using internal project generated asset {placement.asset_id}",
                warnings,
            )

        # Fallback for any other case: generate parametrically.
        return (
            "parametric_generated",
            "parametric_generated",
            f"generating tower {placement.asset_id} parametrically from SceneSpec",
            warnings,
        )

    def resolve_sector_component(
        self,
        sector: SectorSpec,
        component: Literal["antenna", "radio"],
    ) -> tuple[GenerationStrategy, GeometrySource, str, list[str]]:
        """Antennas and radios are currently generated from internal GLBs.

        Exact import is used when dimensions match; otherwise we fall back to
        procedural primitives (stretched_imported_glb is avoided for active
        components because shape distortion is not acceptable).
        """
        warnings: list[str] = []
        asset_id = (
            sector.antenna_asset_id if component == "antenna" else (sector.radio_asset_id or "")
        )
        requested = (
            sector.antenna_dimensions_m if component == "antenna" else sector.radio_dimensions_m
        )

        if not asset_id:
            return (
                "procedural_fallback",
                "degraded",
                f"no {component} asset requested; using procedural primitive",
                warnings,
            )

        asset = self._asset(asset_id)
        if asset is None:
            return (
                "procedural_fallback",
                "degraded",
                f"no manifest for {component} {asset_id}; using procedural primitive",
                warnings,
            )

        if requested is not None and asset.dimensions_m is not None:
            if self._dimensions_match(requested, asset.dimensions_m):
                if asset.source in {"cc_by", "vendor_supplied", "vendor_expected"}:
                    return (
                        "imported_glb_exact",
                        "imported_glb_exact",
                        f"exact validated {component} GLB {asset_id}",
                        warnings,
                    )
                return (
                    "internal_project_generated",
                    "internal_project_generated",
                    f"exact internal {component} GLB {asset_id}",
                    warnings,
                )
            warnings.append(f"{component.upper()}_DIMENSIONS_MISMATCH:{asset_id}")
            return (
                "procedural_fallback",
                "degraded",
                f"{component} asset {asset_id} dimensions mismatch; using procedural primitive",
                warnings,
            )

        if asset.source in {
            "internal_project_generated",
            "internal_cleaned",
            "internal_test_minimal",
        }:
            return (
                "internal_project_generated",
                "internal_project_generated",
                f"using internal {component} asset {asset_id}",
                warnings,
            )

        return (
            "imported_glb_exact",
            "imported_glb_exact",
            f"using {component} asset {asset_id} without dimension verification",
            warnings,
        )

    def resolve_accessory(
        self, placement: SceneAccessoryPlacement
    ) -> tuple[GenerationStrategy, GeometrySource, str, list[str]]:
        """Accessories (cabinet, GPS, etc.) are kept as GLB when available."""
        warnings: list[str] = []
        asset = self._asset(placement.asset_id)
        if asset is None:
            return (
                "procedural_fallback",
                "degraded",
                f"no manifest for accessory {placement.asset_id}; using procedural fallback",
                warnings,
            )

        if placement.dimensions_m is not None and asset.dimensions_m is not None:
            if self._dimensions_match(placement.dimensions_m, asset.dimensions_m):
                if asset.source in {"cc_by", "vendor_supplied", "vendor_expected"}:
                    return (
                        "imported_glb_exact",
                        "imported_glb_exact",
                        f"exact validated accessory GLB {placement.asset_id}",
                        warnings,
                    )
                return (
                    "internal_project_generated",
                    "internal_project_generated",
                    f"exact internal accessory GLB {placement.asset_id}",
                    warnings,
                )
            warnings.append(f"ACCESSORY_DIMENSIONS_MISMATCH:{placement.asset_id}")
            return (
                "procedural_fallback",
                "degraded",
                f"accessory {placement.asset_id} dimensions mismatch; using procedural fallback",
                warnings,
            )

        if asset.source in {
            "internal_project_generated",
            "internal_cleaned",
            "internal_test_minimal",
        }:
            return (
                "internal_project_generated",
                "internal_project_generated",
                f"using internal accessory {placement.asset_id}",
                warnings,
            )

        return (
            "imported_glb_exact",
            "imported_glb_exact",
            f"using accessory {placement.asset_id} without dimension verification",
            warnings,
        )

    def _dimensions_match(self, requested, asset) -> bool:
        """Check whether requested dimensions match an asset within tolerance."""
        for axis in ("width", "depth", "height"):
            req = getattr(requested, axis, None)
            avail = getattr(asset, axis, None)
            if req is None or avail is None or avail == 0:
                return False
            if abs(req - avail) / max(abs(avail), 1e-9) > self.EXACT_DIMENSION_TOLERANCE:
                return False
        return True


def resolve_scene_strategies(scene: SceneSpec, registry: AssetRegistry | None = None) -> SceneSpec:
    """Return a new SceneSpec with generation_strategy/geometry_source filled."""
    resolver = ParametricModelResolver(registry)

    tower_strategy, tower_source, tower_reason, tower_warnings = resolver.resolve_tower(scene.tower)
    tower = scene.tower.model_copy(
        update={
            "generation_strategy": tower_strategy,
            "geometry_source": tower_source,
            "generation_reason": tower_reason,
        }
    )

    sectors: list[SectorSpec] = []
    for sector in scene.sectors:
        ant_strategy, ant_source, ant_reason, _ = resolver.resolve_sector_component(
            sector, "antenna"
        )
        radio_strategy, radio_source, radio_reason, _ = resolver.resolve_sector_component(
            sector, "radio"
        )
        sectors.append(
            sector.model_copy(
                update={
                    "antenna_generation_strategy": ant_strategy,
                    "antenna_geometry_source": ant_source,
                    "radio_generation_strategy": radio_strategy,
                    "radio_geometry_source": radio_source,
                }
            )
        )

    accessories: list[SceneAccessoryPlacement] = []
    for accessory in scene.accessory_assets:
        acc_strategy, acc_source, acc_reason, _ = resolver.resolve_accessory(accessory)
        accessories.append(
            accessory.model_copy(
                update={
                    "generation_strategy": acc_strategy,
                    "geometry_source": acc_source,
                }
            )
        )

    # Aggregate warnings at scene level would need a field; keep them in logs for now.
    if tower_warnings:
        logger.warning("Tower strategy warnings for %s: %s", scene.scene_id, tower_warnings)

    return scene.model_copy(
        update={
            "tower": tower,
            "sectors": sectors,
            "accessory_assets": accessories,
        }
    )
